#!/usr/bin/env ruby
# frozen_string_literal: true
require "exekutor/internal/cli/app"

Process.setproctitle "Exekutor worker (Initializing…) [#{$PROGRAM_NAME}]"

exit Exekutor::Internal::CLI::App.run(ARGV)
